version: '3.8'

services:

  ala-hub:
    image: sbdi/ala-hub-dev
    build:
      context: .
    ports:
      - 8080:8080
    volumes:
      - ./sbdi/data/config/ala-hub-config.properties:/data/ala-hub/config/ala-hub-config.properties
